default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: chewbacon

test:
  <<: *default
  host: localhost
  database: chewbacon_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
